export const GETBANNERLIST = "GETBANNERLIST"
export const GETQUESTIONLIST = "GETQUESTIONLIST"
export const GETSCROLLLIST = "GETSCROLLLIST"
export const GETAIYINBAOLIST = "GETAIYINBAOLIST"
//home
export const GETBORROWCOUNT = "GETBORROWCOUNT"